PUT http://localhost:8080/events/16
content-type:application/json
authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbGwiOiJ0ZXN0QHRlc3QuY29tIiwiZXhwIjoxNzM3MjU2Mzk3LCJ1c2VySUQiOjJ9.-RhW6qfSgaEYySxGctgopVc-I0ZcN2plZ0neHhUcVCQ

{
    "name": "updated test",
    "description": "A update on test event",
    "location": "a updated location" ,
    "dateTime": "2025-01-01T15:30:00.000Z" 
}
 