PUT http://localhost:8080/events/21
content-type: application/json

authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbGwiOiJ0ZXN0M0B0ZXN0LmNvbSIsImV4cCI6MTczNzIzMzUyOCwidXNlcklEIjozfQ.HRtQYk9vebWAa5mUHLh6q-JBGfA43cmSUQRQV2_Uyak

{
    "name": "updated test",
    "description": "A update on test event",
    "location": "a updated location" ,
    "dateTime": "2025-01-01T15:30:00.000Z" 
}
 